// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCECDmRDQ_LMDfZgaMAXkVnC2XeQ6VDjbg',
    appId: '1:564716749555:web:1c947d0f4101f01ca76d86',
    messagingSenderId: '564716749555',
    projectId: 'project-roots-85bbd',
    authDomain: 'project-roots-85bbd.firebaseapp.com',
    storageBucket: 'project-roots-85bbd.appspot.com',
    measurementId: 'G-BYTMEEYB5X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtL5GliTkVY1XFsA21SGRYg9Ym8sf0C-E',
    appId: '1:564716749555:android:76e3ac92185f6592a76d86',
    messagingSenderId: '564716749555',
    projectId: 'project-roots-85bbd',
    storageBucket: 'project-roots-85bbd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhWsdiVbHH487sdEqU31CMZZeGs5i_wjM',
    appId: '1:564716749555:ios:6f41b4623c70a51ca76d86',
    messagingSenderId: '564716749555',
    projectId: 'project-roots-85bbd',
    storageBucket: 'project-roots-85bbd.appspot.com',
    iosClientId: '564716749555-do1d364pppjtqa0ei2qu5mrunt2khtml.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectroots',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhWsdiVbHH487sdEqU31CMZZeGs5i_wjM',
    appId: '1:564716749555:ios:6f41b4623c70a51ca76d86',
    messagingSenderId: '564716749555',
    projectId: 'project-roots-85bbd',
    storageBucket: 'project-roots-85bbd.appspot.com',
    iosClientId: '564716749555-do1d364pppjtqa0ei2qu5mrunt2khtml.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectroots',
  );
}
